ietf-wg-happy/draft-happy-eyeballs-v3

draft-happy-eyeballs-v3.md
=> Add SVCB to the query algorithm

draft-happy-eyeballs-v3.md
=> Update introduction and overview with SVCB

draft-happy-eyeballs-v3.md
=> Add ALPN handling

draft-pauly-v6ops-happy-eyeballs-v3.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/23.
=> Fix typos in Section 5

draft-pauly-v6ops-happy-eyeballs-v3.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/22.
=> Clarify wording in Section 4

draft-pauly-v6ops-happy-eyeballs-v3.md
Closes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/18.
=> Add a note about NAT64 address synthesis

draft-pauly-v6ops-happy-eyeballs-v3.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/36.
=> Remove hint-only addresses after receiving A/AAAA

draft-pauly-v6ops-happy-eyeballs-v3.md
Applied Emacs' `M-x fill-region` for some paragraphs.
=> Correct format and refer to draft-ietf-tls-svcb-ech

charter.md
Editorial updates to charter
Mostly minor wording tweaks, a few updates.
=> Editorial updates to charter

charter.md
=> Remove unclear deliverable from charter

charter.md
=> Clarify out-of-scope

charter.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/51.
=> Add charter text about HE-like uses

charter.md
=> Clarify target type of reporting errors document

charter.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/59.
=> Remove deliverable for documenting effectiveness

charter.md
Fixes https://github.com/tfpauly/draft-happy-eyeballs-v3/issues/61.
=> Specify section 4.3 for RFC 9132 reference

charter.md
Expand on error reporting section in the charter.
Fixes #63
=> Expand on error reporting section in the charter.

draft-pauly-happy-happyeyeballs-v3.md
=> Mark as standards track

draft-ietf-happy-happyeyeballs-v3.md
Fixes https://github.com/ietf-wg-happy/draft-happy-eyeballs-v3/issues/34.
=> Update reference to RFC6724 for Source Address Selection

draft-ietf-happy-happyeyeballs-v3.md
Fixes https://github.com/ietf-wg-happy/draft-happy-eyeballs-v3/issues/37.
=> Update language around responses and records

draft-ietf-happy-happyeyeballs-v3.md
Took a pass at adding some text to support IPv6-mostly networks, open to any feedback and changes.
Closes https://github.com/ietf-wg-happy/draft-happy-eyeballs-v3/issues/41.
=> Support IPv6-mostly networks

draft-ietf-happy-happyeyeballs-v3.md
Rework to resolution to incorporate feedback / issues
=> Rework resolution explantion
